import "jsr:@supabase/functions-js/edge-runtime.d.ts";

const SU=Deno.env.get('SUPABASE_URL')!, SK=Deno.env.get('SUPABASE_SERVICE_ROLE_KEY')!;
const AI='koki-ai-turn-test-agent-staging-v3', ENGINE='KOKI_MARKET_RESEARCH_V68';
const iso=()=>new Date().toISOString();

async function db(path:string,init:RequestInit={}){const h=new Headers(init.headers);h.set('apikey',SK);h.set('Authorization',`Bearer ${SK}`);if(init.body&&!h.has('Content-Type'))h.set('Content-Type','application/json');const r=await fetch(`${SU}/rest/v1/${path}`,{...init,headers:h,signal:init.signal??AbortSignal.timeout(30000)}),t=await r.text();if(!r.ok)throw Error(`db_${r.status}:${t.slice(0,300)}`);return t?JSON.parse(t):null}
async function wk(){return(await db('koki_worker_config?id=eq.worker_key&select=value&limit=1'))?.[0]?.value||''}
async function patchDraft(id:string,p:any){await db(`koki_listing_drafts_v3?id=eq.${encodeURIComponent(id)}`,{method:'PATCH',body:JSON.stringify({...p,updated_at:iso()})})}
function decode(s:any){return String(s??'').replace(/<!\[CDATA\[([\s\S]*?)\]\]>/g,'$1').replace(/&amp;/g,'&').replace(/&quot;/g,'"').replace(/&#39;|&apos;/g,"'").replace(/&lt;/g,'<').replace(/&gt;/g,'>').replace(/&euro;/gi,'€').replace(/&#(\d+);/g,(_,n)=>String.fromCharCode(Number(n)))}
function clean(s:any){return decode(String(s??'').replace(/<script[\s\S]*?<\/script>/gi,' ').replace(/<style[\s\S]*?<\/style>/gi,' ').replace(/<[^>]+>/g,' ')).replace(/\s+/g,' ').trim()}
function domainOf(url:any){try{return new URL(String(url)).hostname.replace(/^www\./,'').toLowerCase()}catch{return''}}
function confirmed(s:any){const o:any={};for(const[k,v]of Object.entries(s||{}) as any)if(v?.status==='CONFIRMED'&&v?.value!=null)o[k]=v.value;return o}
function identityOf(d:any){const f=confirmed(d.fact_snapshot),raw=String(d.listing_content?.title||d.product_context?.product_identity?.canonical_name||d.user_edits?.product_description||'');const storage=String(f.storage_capacity||f.internal_memory||'').replace(/\s+/g,'');return clean(`${raw.replace(/\s*-\s*(използван|нов).*$/i,'')}${storage&&!raw.toLowerCase().includes(storage.toLowerCase())?` ${storage}`:''}`)}
function parseYahooTargets(html:string){const out:any[]=[];const seen=new Set<string>();for(const m of String(html||'').matchAll(/\/RU=([^/]+)\/RK=/g)){let u='';try{u=decodeURIComponent(m[1])}catch{}if(!/^https?:\/\//i.test(u))continue;const d=domainOf(u);if(!d||/(^|\.)yahoo\.|yimg\.|guce\.yahoo\.|advertising\.yahoo\./i.test(d))continue;if(!(d.endsWith('.bg')||d==='mobilebulgaria.com'))continue;const key=u.replace(/[?#].*$/,'').replace(/\/$/,'');if(seen.has(key))continue;seen.add(key);out.push({url:u,domain:d})}return out.slice(0,14)}
async function yahoo(identity:string){const queries=[`"${identity}" цена България`,`"${identity}" магазин България`];const all:any[]=[];for(const q of queries){try{const u=new URL('https://search.yahoo.com/search');u.searchParams.set('p',q);const r=await fetch(u,{headers:{'User-Agent':'Mozilla/5.0 KOKI-Market/68','Accept-Language':'bg-BG,bg;q=0.9,en;q=0.7'},signal:AbortSignal.timeout(15000)});if(r.ok)all.push(...parseYahooTargets(await r.text()))}catch{}await new Promise(r=>setTimeout(r,300))}const seen=new Set<string>();return all.filter(x=>{const k=x.url.replace(/[?#].*$/,'').replace(/\/$/,'');if(seen.has(k))return false;seen.add(k);return true}).slice(0,12)}
function moneyContexts(raw:string){const out:string[]=[];const re=/(?:€|EUR|лв\.?|BGN)\s*[0-9][0-9\s.,]*|[0-9][0-9\s.,]*\s*(?:€|EUR|лв\.?|BGN)/gi;let m;while((m=re.exec(raw))&&out.length<14){out.push(clean(raw.slice(Math.max(0,m.index-260),Math.min(raw.length,m.index+m[0].length+260))))}return out}
async function evidence(x:any){try{const r=await fetch(x.url,{headers:{'User-Agent':'Mozilla/5.0 KOKI-Market/68','Accept-Language':'bg-BG,bg;q=0.9,en;q=0.7'},redirect:'follow',signal:AbortSignal.timeout(12000)});if(!r.ok)return{...x,http:r.status,title:'',evidence:[]};const raw=(await r.text()).slice(0,900000),title=clean(raw.match(/<title[^>]*>([\s\S]*?)<\/title>/i)?.[1]||''),ctx=moneyContexts(raw);for(const m of raw.matchAll(/"price"\s*:\s*"?([0-9]+(?:\.[0-9]+)?)"?[\s\S]{0,250}?"priceCurrency"\s*:\s*"([A-Z]{3})"/gi)){ctx.unshift(clean(`structured price ${m[1]} ${m[2]}`));if(ctx.length>=16)break}for(const m of raw.matchAll(/"name"\s*:\s*"([^"]{3,180})"[\s\S]{0,700}?"price"\s*:\s*\{[\s\S]{0,300}?"currencyIso"\s*:\s*"([A-Z]{3})"[\s\S]{0,220}?"value"\s*:\s*([0-9]+(?:\.[0-9]+)?)/gi)){ctx.unshift(clean(`product ${decode(m[1])} price ${m[3]} ${m[2]}`));if(ctx.length>=18)break}return{...x,http:r.status,title,evidence:[...new Set(ctx)].slice(0,18)}}catch(e){return{...x,http:0,title:'',evidence:[],error:String((e as any)?.message||e).slice(0,120)}}}
const PROMPT=`You are KOKI MARKET EVIDENCE CLASSIFIER for Bulgaria. Work ONLY from the supplied merchant-page evidence. Confirmed product facts are absolute authority. Never invent a URL, merchant, price, condition, storage, model, generation or availability. Every accepted URL MUST be copied exactly from candidate_pages and every accepted price MUST be explicitly visible in that page's evidence.

Goal 1: USED_MARKET only when at least 3 individual current USED/private-market product offers match the exact identity. Refurbished-shop category pages, price aggregators, accessories, wanted ads, bundles and wrong variants do not count.

Goal 2: if Goal 1 fails, NEW_RETAIL_FALLBACK only when at least 3 DISTINCT merchant domains contain the exact NEW product/variant with an observed current price. Reject price aggregators (for example Pazaruvaj/Mobile Bulgaria), refurbished sellers, category pages where the evidence does not bind the exact variant to the price, and any page with ambiguous product-price pairing.

Currency output is EUR. Convert an explicitly observed BGN price using exactly 1 EUR = 1.95583 BGN. If neither rule is met, return INSUFFICIENT. Never return RUNNING.

Return strict JSON: {status:'READY|INSUFFICIENT',research_method:'USED_MARKET|NEW_RETAIL_FALLBACK|NONE',accepted_used_listings:[{title,url,price_eur,classification:'EXACT|STRONG_COMPARABLE',reason_bg}],retail_sources:[{merchant,url,price_eur,reason_bg}],summary_bg,confidence:'HIGH|MEDIUM|LOW'}.`;
function validShape(r:any){return!!r&&['READY','INSUFFICIENT'].includes(r.status)&&['USED_MARKET','NEW_RETAIL_FALLBACK','NONE'].includes(r.research_method)}
function validateEvidence(r:any,pages:any[]){if(!validShape(r))return{ok:false,reason:'SHAPE'};if(r.status==='INSUFFICIENT')return{ok:r.research_method==='NONE',reason:'INSUFFICIENT'};const byUrl=new Map(pages.map(x=>[x.url,x]));if(r.research_method==='USED_MARKET'){const a=Array.isArray(r.accepted_used_listings)?r.accepted_used_listings:[];if(a.length<3)return{ok:false,reason:'USED_LT3'};for(const x of a)if(!byUrl.has(x.url)||!(Number(x.price_eur)>0))return{ok:false,reason:'USED_UNGROUNDED'};return{ok:true,reason:'USED'}}const a=Array.isArray(r.retail_sources)?r.retail_sources:[];if(a.length<3)return{ok:false,reason:'RETAIL_LT3'};const ds=new Set<string>();for(const x of a){if(!byUrl.has(x.url)||!(Number(x.price_eur)>0))return{ok:false,reason:'RETAIL_UNGROUNDED'};ds.add(domainOf(x.url))}return{ok:ds.size>=3,reason:ds.size>=3?'RETAIL':'RETAIL_DOMAINS_LT3'}}
async function classify(d:any,pages:any[]){const key=await wk(),input={canonical_product:identityOf(d),confirmed_product_facts:confirmed(d.fact_snapshot),condition:confirmed(d.fact_snapshot).state||confirmed(d.fact_snapshot).condition||'',target_price_eur:Number(d.owner_desired_price_eur||0),candidate_pages:pages};const r=await fetch(`${SU}/functions/v1/${AI}`,{method:'POST',headers:{'Content-Type':'application/json','x-koki-worker':key},body:JSON.stringify({domain:'NEW_LISTING',stage:'MARKET_EVIDENCE_V68',subject_id:d.id,system:PROMPT,input,media:[],temp:.02,cache_ttl_seconds:900,allow_emergency_groq:false}),signal:AbortSignal.timeout(95000)}),j=await r.json().catch(()=>({}));if(!r.ok||!j.ok)throw Error(String(j.error||j.error_class||`AI_${r.status}`));const v=validateEvidence(j.data,pages);if(!v.ok)throw Error(`EVIDENCE_VALIDATION_${v.reason}`);return{data:j.data,provider:j.provider||j.source||null,model:j.model||null}}
function stats(v:any[]){const a=v.map(Number).filter(x=>Number.isFinite(x)&&x>0).sort((a,b)=>a-b);if(!a.length)return null;const mean=a.reduce((s,x)=>s+x,0)/a.length,median=a.length%2?a[(a.length-1)/2]:(a[a.length/2-1]+a[a.length/2])/2;return{n:a.length,min:a[0],max:a[a.length-1],mean,median}}
function tier(price:number,mean:number){const p=price/mean;if(p<.85)return['GREAT_DEAL','Отлична цена'];if(p<.95)return['GOOD_DEAL','Добра цена'];if(p<=1.05)return['FAIR_MARKET','Пазарна цена'];if(p<=1.15)return['ELEVATED','Над средната'];return['HIGH_OUTLIER','Висока цена']}
function tierRows(mean:number){return[{tier:'GREAT_DEAL',label_bg:'Отлична цена',min_eur:0,max_eur:+(.85*mean).toFixed(2)},{tier:'GOOD_DEAL',label_bg:'Добра цена',min_eur:+(.85*mean).toFixed(2),max_eur:+(.95*mean).toFixed(2)},{tier:'FAIR_MARKET',label_bg:'Пазарна цена',min_eur:+(.95*mean).toFixed(2),max_eur:+(1.05*mean).toFixed(2)},{tier:'ELEVATED',label_bg:'Над средната',min_eur:+(1.05*mean).toFixed(2),max_eur:+(1.15*mean).toFixed(2)},{tier:'HIGH_OUTLIER',label_bg:'Висока цена',min_eur:+(1.15*mean).toFixed(2),max_eur:null}]}
function materialize(r:any,target:number){if(r.status!=='READY')return null;if(r.research_method==='USED_MARKET'){const a=r.accepted_used_listings,s=stats(a.map((x:any)=>x.price_eur));if(!s||s.n<3)return null;const t=tier(target,s.mean);return{method:'USED_MARKET',comparables:a.map((x:any)=>({title:clean(x.title),source_ref:x.url,price_eur:Number(x.price_eur),classification:x.classification,reason_bg:clean(x.reason_bg)})),range_low_eur:+s.min.toFixed(2),range_high_eur:+s.max.toFixed(2),mean_eur:+s.mean.toFixed(2),median_eur:+s.median.toFixed(2),new_average_eur:null,used_baseline_eur:null,tiers:tierRows(s.mean),target_evaluation:{target_price_eur:target,tier:t[0],tier_code:t[0],tier_label_bg:t[1],difference_from_mean_eur:+(target-s.mean).toFixed(2),difference_from_mean_percent:+(((target-s.mean)/s.mean)*100).toFixed(2),rationale_bg:`Спрямо ${s.n} проверени употребявани оферти.`}}}const a=r.retail_sources,s=stats(a.map((x:any)=>x.price_eur));if(!s||s.n<3)return null;const baseline=s.mean/2,t=tier(target,baseline);return{method:'NEW_RETAIL_FALLBACK',comparables:a.map((x:any)=>({title:clean(x.merchant),source_ref:x.url,price_eur:Number(x.price_eur),classification:'NEW_RETAIL',reason_bg:clean(x.reason_bg)})),range_low_eur:+(.85*baseline).toFixed(2),range_high_eur:+(1.15*baseline).toFixed(2),mean_eur:+baseline.toFixed(2),median_eur:+baseline.toFixed(2),new_average_eur:+s.mean.toFixed(2),used_baseline_eur:+baseline.toFixed(2),tiers:tierRows(baseline),target_evaluation:{target_price_eur:target,tier:t[0],tier_code:t[0],tier_label_bg:t[1],difference_from_mean_eur:+(target-baseline).toFixed(2),difference_from_mean_percent:+(((target-baseline)/baseline)*100).toFixed(2),rationale_bg:`Ориентирът е 50% от средната цена на ${s.n} проверени нови оферти.`}}}
async function run(id:string){const d=(await db(`koki_listing_drafts_v3?id=eq.${encodeURIComponent(id)}&select=*&limit=1`))?.[0];if(!d)throw Error('draft_not_found');await patchDraft(id,{research_substate:'RUNNING'});const identity=identityOf(d),targets=await yahoo(identity),pages=(await Promise.all(targets.map(evidence))).filter(x=>x.http===200&&x.evidence?.length),target=Number(d.owner_desired_price_eur||0);try{const a=await classify(d,pages),ready=materialize(a.data,target);if(!ready)throw Error('READY_MATERIALIZATION_FAILED');const mc={state:'READY',...ready,confidence:a.data.confidence||'MEDIUM',price_authority:true,accepted_count:ready.comparables.length,summary_bg:clean(a.data.summary_bg)||`Пазарното сравнение е базирано на ${ready.comparables.length} проверени източника.`,source:ENGINE,dataset_count:pages.length,provider:a.provider,model:a.model,updated_at:iso()};await patchDraft(id,{research_state:'COMPLETED',research_substate:'COMPLETED_OK',research_result:{result_code:'OK',operational_price_authority:true,market_method:ready.method,market_summary_bg:mc.summary_bg},research_validation:{accepted_count:ready.comparables.length,stopping_rule_met:true,collector_version:'yahoo-direct-page-evidence-v68',collected_at:iso(),candidate_pages:pages.length},research_version:Math.max(1,Number(d.research_version||0)+1),market_comparison:mc});return{ok:true,draft_id:id,state:'COMPLETED_OK',identity,candidate_pages:pages.length,market_comparison:mc}}catch(e){const msg=String((e as any)?.message||e),summary=`Проверих ${pages.length} директни страници за ${identity}, но не потвърдих минимум 3 независими сравними цени. Пазарен диапазон няма да бъде измислян.`,mc={state:'INSUFFICIENT',method:'NONE',confidence:'LOW',price_authority:false,accepted_count:0,comparables:[],tiers:[],summary_bg:summary,source:ENGINE,error:msg.slice(0,180),dataset_count:pages.length,updated_at:iso()};await patchDraft(id,{research_state:'COMPLETED',research_substate:'COMPLETED_INSUFFICIENT',research_result:{result_code:'INSUFFICIENT_MARKET_EVIDENCE',operational_price_authority:false,error:msg.slice(0,260),summary_bg:summary},research_validation:{accepted_count:0,stopping_rule_met:false,collector_version:'yahoo-direct-page-evidence-v68',collected_at:iso(),candidate_pages:pages.length},research_version:Math.max(1,Number(d.research_version||0)+1),market_comparison:mc});return{ok:true,draft_id:id,state:'COMPLETED_INSUFFICIENT',identity,candidate_pages:pages.length,market_comparison:mc,degraded:true}}}
Deno.serve(async req=>{try{const key=await wk();if(!key||req.headers.get('x-koki-worker')!==key)return Response.json({ok:false,error:'forbidden'},{status:403});const b=await req.json().catch(()=>({}));if(b.action==='qa'){const sample='<a href="https://r.search.yahoo.com/x/RU=https%3a%2f%2fshop.bg%2fp%2f1/RK=2/RS=x">x</a><a href="https://r.search.yahoo.com/x/RU=https%3a%2f%2fshop.bg%2fp%2f1/RK=2/RS=x">x</a><a href="https://r.search.yahoo.com/x/RU=https%3a%2f%2fother.bg%2fp/RK=2/RS=x">x</a>',targets=parseYahooTargets(sample),pages=[{url:'https://a.bg/p',domain:'a.bg'},{url:'https://b.bg/p',domain:'b.bg'},{url:'https://c.bg/p',domain:'c.bg'}],good={status:'READY',research_method:'NEW_RETAIL_FALLBACK',accepted_used_listings:[],retail_sources:[{merchant:'A',url:'https://a.bg/p',price_eur:1000},{merchant:'B',url:'https://b.bg/p',price_eur:1100},{merchant:'C',url:'https://c.bg/p',price_eur:900}]},bad={...good,retail_sources:[{merchant:'X',url:'https://invented.bg/p',price_eur:1},{merchant:'B',url:'https://b.bg/p',price_eur:1100},{merchant:'C',url:'https://c.bg/p',price_eur:900}]},mat=materialize(good,500),tests={yahoo_decode:targets.length===2&&targets[0].url==='https://shop.bg/p/1',reject_invented_url:validateEvidence(bad,pages).ok===false,retail_3_domains:validateEvidence(good,pages).ok===true,deterministic_baseline:mat?.used_baseline_eur===500&&mat?.range_low_eur===425&&mat?.range_high_eur===575};return Response.json({ok:Object.values(tests).every(Boolean),engine:ENGINE,tests})}if((b.action==='research'||b.action==='qa_canary')&&b.draft_id)return Response.json(await run(String(b.draft_id)));return Response.json({ok:false,error:'unsupported_action'},{status:400})}catch(e){return Response.json({ok:false,error:String((e as any)?.message||e)},{status:500})}});
