import "jsr:@supabase/functions-js/edge-runtime.d.ts";

const SU=Deno.env.get('SUPABASE_URL')!, SK=Deno.env.get('SUPABASE_SERVICE_ROLE_KEY')!;
const OLX='https://www.olx.bg/api/partner', TOKEN='https://www.olx.bg/api/open/oauth/token';
const CID=Deno.env.get('OLX_CLIENT_ID')||'200513';
const ENGINE='KOKI_MARKET_RESEARCH_AI_ONLY_V70';
const FREE_GROUND_MODELS=['gemini-2.5-flash','gemini-2.5-flash-lite'];
const iso=()=>new Date().toISOString();
const clean=(v:any)=>String(v??'').replace(/\s+/g,' ').trim();

async function db(path:string,init:RequestInit={}){const h=new Headers(init.headers);h.set('apikey',SK);h.set('Authorization',`Bearer ${SK}`);if(init.body&&!h.has('Content-Type'))h.set('Content-Type','application/json');const r=await fetch(`${SU}/rest/v1/${path}`,{...init,headers:h,signal:init.signal??AbortSignal.timeout(30000)}),t=await r.text();if(!r.ok)throw Error(`db_${r.status}:${t.slice(0,300)}`);return t?JSON.parse(t):null}
async function rpc(name:string,body:any){return db(`rpc/${name}`,{method:'POST',body:JSON.stringify(body)})}
async function wk(){return(await db('koki_worker_config?id=eq.worker_key&select=value&limit=1'))?.[0]?.value||''}
async function patchDraft(id:string,p:any){await db(`koki_listing_drafts_v3?id=eq.${encodeURIComponent(id)}`,{method:'PATCH',body:JSON.stringify({...p,updated_at:iso()})})}
function confirmed(s:any){const o:any={};for(const[k,v]of Object.entries(s||{}) as any)if(v?.status==='CONFIRMED'&&v?.value!=null)o[k]=v.value;return o}
function identityOf(d:any){const f=confirmed(d.fact_snapshot),raw=clean(d.listing_content?.title||d.product_context?.product_identity?.canonical_name||d.user_edits?.product_description||'');const storage=clean(f.storage_capacity||f.internal_memory||'').replace(/\s+/g,'');return clean(`${raw.replace(/\s*-\s*(използван|нов).*$/i,'')}${storage&&!raw.toLowerCase().includes(storage.toLowerCase())?` ${storage}`:''}`)}
function domainOf(url:any){try{return new URL(String(url)).hostname.replace(/^www\./,'').toLowerCase()}catch{return''}}
function normUrl(url:any){try{const u=new URL(String(url));u.hash='';for(const k of [...u.searchParams.keys()])if(/^utm_|^(gclid|fbclid)$/i.test(k))u.searchParams.delete(k);return u.toString().replace(/\/$/,'')}catch{return clean(url)}}

async function refreshLock(aid:string,owner:string){for(let i=0;i<8;i++){if(await rpc('koki_claim_olx_refresh_v1',{p_account_id:aid,p_owner:owner,p_lease_seconds:30}).catch(()=>false))return true;await new Promise(r=>setTimeout(r,250))}return false}
async function olxToken(aid:string){let t=(await db(`koki_olx_credentials?olx_account_id=eq.${encodeURIComponent(aid)}&select=access_token,refresh_token,expires_at&limit=1`))?.[0];if(!t)return null;if(Date.parse(t.expires_at)-Date.now()>120000)return t.access_token;const owner=crypto.randomUUID();if(!await refreshLock(aid,owner))return null;try{t=(await db(`koki_olx_credentials?olx_account_id=eq.${encodeURIComponent(aid)}&select=access_token,refresh_token,expires_at&limit=1`))?.[0];if(!t)return null;if(Date.parse(t.expires_at)-Date.now()>120000)return t.access_token;const secret=Deno.env.get('OLX_CLIENT_SECRET');if(!secret)return null;const r=await fetch(TOKEN,{method:'POST',headers:{'Content-Type':'application/x-www-form-urlencoded'},body:new URLSearchParams({grant_type:'refresh_token',client_id:CID,client_secret:secret,refresh_token:t.refresh_token}),signal:AbortSignal.timeout(15000)});if(!r.ok)return null;const n=await r.json();await db(`koki_olx_credentials?olx_account_id=eq.${encodeURIComponent(aid)}`,{method:'PATCH',body:JSON.stringify({access_token:n.access_token,refresh_token:n.refresh_token||t.refresh_token,expires_at:new Date(Date.now()+Number(n.expires_in||86400)*1000).toISOString(),refreshed_at:iso(),updated_at:iso()})});return n.access_token}finally{await rpc('koki_release_olx_refresh_v1',{p_account_id:aid,p_owner:owner}).catch(()=>{})}}
async function olxCategorySuggestion(d:any,identity:string){try{if(!d.olx_account_id||identity.length<3)return[];const token=await olxToken(String(d.olx_account_id));if(!token)return[];const r=await fetch(`${OLX}/categories/suggestion?q=${encodeURIComponent(identity)}`,{headers:{Authorization:`Bearer ${token}`,Version:'2.0',Accept:'application/json','Accept-Language':'bg'},signal:AbortSignal.timeout(15000)});if(!r.ok)return[];const j=await r.json().catch(()=>[]),x=j?.data??j;return Array.isArray(x)?x.slice(0,8):[]}catch{return[]}}

function creds(){return [['A',Deno.env.get('GEMINI_API_KEY')],['B',Deno.env.get('GEMINI_API_KEY_B')],['C',Deno.env.get('GEMINI_API_KEY_C')],['D',Deno.env.get('GEMINI_API_KEY_D')],['E',Deno.env.get('GEMINI_API_KEY_E')],['F',Deno.env.get('GEMINI_API_KEY_F')],['G',Deno.env.get('GEMINI_API_KEY_G')],['H',Deno.env.get('GEMINI_API_KEY_H')]].filter(x=>!!x[1]) as [string,string][]}
async function availableModels(key:string){try{const r=await fetch('https://generativelanguage.googleapis.com/v1beta/models?pageSize=1000',{headers:{'x-goog-api-key':key},signal:AbortSignal.timeout(10000)});if(!r.ok)return[];const j=await r.json();return (j.models||[]).filter((m:any)=>(m.supportedGenerationMethods||[]).includes('generateContent')).map((m:any)=>String(m.name||'').replace(/^models\//,''))}catch{return[]}}
async function groundingModels(key:string){const available=new Set(await availableModels(key));return FREE_GROUND_MODELS.filter(m=>available.has(m))}
function parseJson(text:string){const t=String(text||'').replace(/<think>[\s\S]*?<\/think>/gi,'').replace(/^```json\s*/i,'').replace(/```$/,'').trim();try{return JSON.parse(t)}catch{const a=t.indexOf('{'),b=t.lastIndexOf('}');if(a>=0&&b>a)try{return JSON.parse(t.slice(a,b+1))}catch{}return null}}
function outText(j:any){return (j?.candidates||[]).flatMap((c:any)=>c?.content?.parts||[]).map((p:any)=>p?.text||'').join('\n').trim()}
function grounding(j:any){return (j?.candidates?.[0]?.groundingMetadata?.groundingChunks||[]).map((x:any,i:number)=>({index:i,url:clean(x?.web?.uri||''),title:clean(x?.web?.title||''),domain:domainOf(x?.web?.uri||'')})).filter((x:any)=>x.url)}

const PROMPT=`You are KOKI AI-ONLY MARKET ANALYST for Bulgaria. You MUST use Google Search grounding. There is NO deterministic web collector and NO pre-supplied search dataset. Search the live web yourself and reason from grounded evidence only.

Confirmed product facts are absolute authority. OLX category suggestions are taxonomy hints only, never price evidence. Never change model, storage, generation, variant or condition to make results fit. Never invent a listing, merchant, URL, price, availability or product fact.

STEP 1 — USED MARKET. Search current public Bulgarian USED/private-market listings for the exact product. Prefer OLX Bulgaria when available, but other current Bulgarian secondary-market sources are allowed. Accept EXACT or STRONG_COMPARABLE only. Reject wrong model/storage/generation/variant, accessories, wanted ads, bundles, duplicate URLs, listings without a visible observed price, and stale/removed offers when the grounded evidence indicates that. If at least 3 valid used listings exist, return USED_MARKET.

STEP 2 — RETAIL FALLBACK. Only if fewer than 3 valid used listings exist, search the exact NEW product in Bulgaria. Require at least 3 DISTINCT merchant domains, each with a visible observed current price for the exact variant. Reject price aggregators as merchants, refurbished sellers as NEW retail, category pages without a clear product-price binding, wrong variants and unavailable/stale prices when indicated. If this rule is met, return NEW_RETAIL_FALLBACK.

All monetary output must be EUR. Convert an explicitly observed BGN price using exactly 1 EUR = 1.95583 BGN. Never infer a missing price.

Return strict JSON only: {status:'READY|INSUFFICIENT',research_method:'USED_MARKET|NEW_RETAIL_FALLBACK|NONE',accepted_used_listings:[{title,url,price_eur,classification:'EXACT|STRONG_COMPARABLE',reason_bg}],retail_sources:[{merchant,url,price_eur,reason_bg}],summary_bg,confidence:'HIGH|MEDIUM|LOW'}.
If neither rule is met, return INSUFFICIENT/NONE. Never return RUNNING.`;

function validateGrounded(r:any,chunks:any[]){if(!r||!['READY','INSUFFICIENT'].includes(r.status)||!['USED_MARKET','NEW_RETAIL_FALLBACK','NONE'].includes(r.research_method))return{ok:false,reason:'SHAPE'};if(r.status==='INSUFFICIENT')return{ok:r.research_method==='NONE',reason:'INSUFFICIENT'};const domains=new Set(chunks.map(x=>x.domain).filter(Boolean));if(r.research_method==='USED_MARKET'){const a=Array.isArray(r.accepted_used_listings)?r.accepted_used_listings:[];const seen=new Set();for(const x of a){const u=normUrl(x.url),d=domainOf(u);if(!/^https?:\/\//i.test(u)||!(Number(x.price_eur)>0)||!d||!domains.has(d)||seen.has(u))return{ok:false,reason:'USED_UNGROUNDED_OR_DUP'};seen.add(u)}return{ok:a.length>=3,reason:a.length>=3?'USED':'USED_LT3'}}const a=Array.isArray(r.retail_sources)?r.retail_sources:[],seenD=new Set();for(const x of a){const u=normUrl(x.url),d=domainOf(u);if(!/^https?:\/\//i.test(u)||!(Number(x.price_eur)>0)||!d||!domains.has(d)||seenD.has(d))return{ok:false,reason:'RETAIL_UNGROUNDED_OR_DUP_DOMAIN'};seenD.add(d)}return{ok:a.length>=3&&seenD.size>=3,reason:a.length>=3&&seenD.size>=3?'RETAIL':'RETAIL_LT3'}}
async function groundedReport(d:any,categorySuggestions:any[]){const identity=identityOf(d),facts=confirmed(d.fact_snapshot),input={canonical_product:identity,confirmed_product_facts:facts,condition:facts.state||facts.condition||'',target_price_eur:Number(d.owner_desired_price_eur||0),validated_olx_category:d.category||null,olx_category_suggestions:categorySuggestions,market:'Bulgaria',currency:'EUR'};let last='FREE_GROUNDING_MODEL_UNAVAILABLE';for(const[label,key]of creds()){const ms=await groundingModels(key);if(!ms.length)continue;for(const model of ms){try{const r=await fetch(`https://generativelanguage.googleapis.com/v1beta/models/${model}:generateContent`,{method:'POST',headers:{'x-goog-api-key':key,'Content-Type':'application/json'},body:JSON.stringify({systemInstruction:{parts:[{text:PROMPT}]},contents:[{role:'user',parts:[{text:JSON.stringify(input)}]}],tools:[{google_search:{}}],generationConfig:{temperature:0.03,candidateCount:1}}),signal:AbortSignal.timeout(75000)}),raw=await r.text();let j:any={};try{j=JSON.parse(raw)}catch{}const chunks=grounding(j),data=parseJson(outText(j)),v=validateGrounded(data,chunks);if(r.ok&&chunks.length&&v.ok)return{data,chunks,provider:'GEMINI_GOOGLE_SEARCH',model,credential:label};last=String(j?.error?.message||(!chunks.length?'NO_GROUNDING_EVIDENCE':`VALIDATION_${v.reason}`)).slice(0,300);if([400,404,429].includes(r.status))continue;if([401,403].includes(r.status))break}catch(e){last=String((e as any)?.message||e)}}}throw Error(last)}

function stats(values:any[]){const a=values.map(Number).filter(x=>Number.isFinite(x)&&x>0).sort((x,y)=>x-y);if(!a.length)return null;const mean=a.reduce((s,x)=>s+x,0)/a.length,median=a.length%2?a[(a.length-1)/2]:(a[a.length/2-1]+a[a.length/2])/2;return{n:a.length,min:a[0],max:a[a.length-1],mean,median}}
function tierFor(price:number,mean:number){const p=price/mean;if(p<.85)return['GREAT_DEAL','Отлична цена'];if(p<.95)return['GOOD_DEAL','Добра цена'];if(p<=1.05)return['FAIR_MARKET','Пазарна цена'];if(p<=1.15)return['ELEVATED','Над средната'];return['HIGH_OUTLIER','Висока цена']}
function tiers(mean:number){return[{tier:'GREAT_DEAL',label_bg:'Отлична цена',min_eur:0,max_eur:+(.85*mean).toFixed(2)},{tier:'GOOD_DEAL',label_bg:'Добра цена',min_eur:+(.85*mean).toFixed(2),max_eur:+(.95*mean).toFixed(2)},{tier:'FAIR_MARKET',label_bg:'Пазарна цена',min_eur:+(.95*mean).toFixed(2),max_eur:+(1.05*mean).toFixed(2)},{tier:'ELEVATED',label_bg:'Над средната',min_eur:+(1.05*mean).toFixed(2),max_eur:+(1.15*mean).toFixed(2)},{tier:'HIGH_OUTLIER',label_bg:'Висока цена',min_eur:+(1.15*mean).toFixed(2),max_eur:null}]}
function materialize(r:any,target:number){if(!r||r.status!=='READY')return null;if(r.research_method==='USED_MARKET'){const a=r.accepted_used_listings,s=stats(a.map((x:any)=>x.price_eur));if(!s||s.n<3)return null;const t=tierFor(target,s.mean);return{method:'USED_MARKET',comparables:a.map((x:any)=>({title:clean(x.title),source_ref:normUrl(x.url),price_eur:Number(x.price_eur),classification:x.classification||'EXACT',reason_bg:clean(x.reason_bg)})),range_low_eur:+s.min.toFixed(2),range_high_eur:+s.max.toFixed(2),mean_eur:+s.mean.toFixed(2),median_eur:+s.median.toFixed(2),new_average_eur:null,used_baseline_eur:null,tiers:tiers(s.mean),target_evaluation:{target_price_eur:target,tier:t[0],tier_code:t[0],tier_label_bg:t[1],difference_from_mean_eur:+(target-s.mean).toFixed(2),difference_from_mean_percent:+(((target-s.mean)/s.mean)*100).toFixed(2),rationale_bg:`Спрямо средната цена от ${s.n} проверени употребявани оферти.`}}}const a=r.retail_sources,s=stats(a.map((x:any)=>x.price_eur));if(!s||s.n<3)return null;const baseline=s.mean/2,t=tierFor(target,baseline);return{method:'NEW_RETAIL_FALLBACK',comparables:a.map((x:any)=>({title:clean(x.merchant),source_ref:normUrl(x.url),price_eur:Number(x.price_eur),classification:'NEW_RETAIL',reason_bg:clean(x.reason_bg)})),range_low_eur:+((baseline)*.70).toFixed(2),range_high_eur:+((baseline)*1.30).toFixed(2),mean_eur:+baseline.toFixed(2),median_eur:+baseline.toFixed(2),new_average_eur:+s.mean.toFixed(2),used_baseline_eur:+baseline.toFixed(2),tiers:tiers(baseline),target_evaluation:{target_price_eur:target,tier:t[0],tier_code:t[0],tier_label_bg:t[1],difference_from_mean_eur:+(target-baseline).toFixed(2),difference_from_mean_percent:+(((target-baseline)/baseline)*100).toFixed(2),rationale_bg:`Ориентирът за употребяван продукт е 50% от средната цена на ${s.n} проверени нови оферти.`}}}

async function run(id:string){const d=(await db(`koki_listing_drafts_v3?id=eq.${encodeURIComponent(id)}&select=*&limit=1`))?.[0];if(!d)throw Error('draft_not_found');await patchDraft(id,{research_substate:'RUNNING'});const identity=identityOf(d),target=Number(d.owner_desired_price_eur||0),categorySuggestions=await olxCategorySuggestion(d,identity);try{const g=await groundedReport(d,categorySuggestions),ready=materialize(g.data,target);if(!ready)throw Error('READY_MATERIALIZATION_FAILED');const mc={state:'READY',...ready,confidence:g.data.confidence||'MEDIUM',price_authority:true,accepted_count:ready.comparables.length,summary_bg:clean(g.data.summary_bg)||`Пазарното сравнение е базирано на ${ready.comparables.length} AI-grounded източника.`,source:ENGINE,provider:g.provider,model:g.model,grounding_count:g.chunks.length,grounding_sources:g.chunks.slice(0,20),olx_category_suggestions:categorySuggestions,updated_at:iso()};await patchDraft(id,{research_state:'COMPLETED',research_substate:'COMPLETED_OK',research_result:{result_code:'OK',operational_price_authority:true,market_method:ready.method,market_summary_bg:mc.summary_bg},research_validation:{accepted_count:ready.comparables.length,stopping_rule_met:true,collector_version:'NONE_AI_ONLY_FREE_GROUNDING_V70',collected_at:iso(),grounding_count:g.chunks.length,olx_category_suggestion_count:categorySuggestions.length},research_version:Math.max(1,Number(d.research_version||0)+1),market_comparison:mc});return{ok:true,draft_id:id,state:'COMPLETED_OK',identity,market_comparison:mc}}catch(e){const msg=String((e as any)?.message||e),summary=`AI провери текущия пазар за ${identity}, но не потвърди минимум 3 надеждни сравними цени. Пазарен диапазон няма да бъде измислян.`,mc={state:'INSUFFICIENT',method:'NONE',confidence:'LOW',price_authority:false,accepted_count:0,comparables:[],tiers:[],target_evaluation:null,summary_bg:summary,source:ENGINE,error:msg.slice(0,180),olx_category_suggestions:categorySuggestions,updated_at:iso()};await patchDraft(id,{research_state:'COMPLETED',research_substate:'COMPLETED_INSUFFICIENT',research_result:{result_code:'INSUFFICIENT_MARKET_EVIDENCE',operational_price_authority:false,error:msg.slice(0,260),summary_bg:summary},research_validation:{accepted_count:0,stopping_rule_met:false,collector_version:'NONE_AI_ONLY_FREE_GROUNDING_V70',collected_at:iso(),olx_category_suggestion_count:categorySuggestions.length},research_version:Math.max(1,Number(d.research_version||0)+1),market_comparison:mc});return{ok:true,draft_id:id,state:'COMPLETED_INSUFFICIENT',identity,market_comparison:mc,degraded:true}}}

Deno.serve(async req=>{try{const key=await wk();if(!key||req.headers.get('x-koki-worker')!==key)return Response.json({ok:false,error:'forbidden'},{status:403});const b=await req.json().catch(()=>({}));if(b.action==='qa'){const used=materialize({status:'READY',research_method:'USED_MARKET',accepted_used_listings:[{title:'a',url:'https://olx.bg/a',price_eur:400},{title:'b',url:'https://olx.bg/b',price_eur:500},{title:'c',url:'https://olx.bg/c',price_eur:600}]},500),retail=materialize({status:'READY',research_method:'NEW_RETAIL_FALLBACK',retail_sources:[{merchant:'a',url:'https://a.bg/1',price_eur:1000},{merchant:'b',url:'https://b.bg/2',price_eur:1100},{merchant:'c',url:'https://c.bg/3',price_eur:900}]},500),tests={ai_only_engine:true,no_collector:'NONE_AI_ONLY_FREE_GROUNDING_V70'.startsWith('NONE_'),free_grounding_policy:FREE_GROUND_MODELS.every(m=>m.startsWith('gemini-2.5-')),used_mean:used?.mean_eur===500&&used?.range_low_eur===400&&used?.range_high_eur===600,retail_formula:retail?.new_average_eur===1000&&retail?.used_baseline_eur===500&&retail?.range_low_eur===350&&retail?.range_high_eur===650,tier_boundaries:retail?.tiers?.[2]?.min_eur===475&&retail?.tiers?.[2]?.max_eur===525};return Response.json({ok:Object.values(tests).every(Boolean),engine:ENGINE,architecture:'AI_ONLY',tests})}if(b.action==='qa_models'){const out=[];for(const[label,key]of creds())out.push({credential:label,free_grounding_models:await groundingModels(key)});return Response.json({ok:true,engine:ENGINE,models:out})}if(b.action==='qa_category'&&b.draft_id){const d=(await db(`koki_listing_drafts_v3?id=eq.${encodeURIComponent(String(b.draft_id))}&select=*&limit=1`))?.[0];if(!d)return Response.json({ok:false,error:'draft_not_found'},{status:404});const identity=identityOf(d),suggestions=await olxCategorySuggestion(d,identity);return Response.json({ok:suggestions.length>0,identity,suggestions})}if((b.action==='research'||b.action==='qa_canary')&&b.draft_id)return Response.json(await run(String(b.draft_id)));return Response.json({ok:false,error:'unsupported_action'},{status:400})}catch(e){return Response.json({ok:false,error:String((e as any)?.message||e)},{status:500})}});